services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tubes2-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - tubes2-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tubes2-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - tubes2-net

networks:
  tubes2-net:
    driver: bridge
